#
# Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
#

Import('VRouterEnv')
env = VRouterEnv.Clone()

vrouter_suite = []

#kernel module
vr_root = './'
makefile = vr_root + 'Makefile'
dp_dir = Dir(vr_root).srcnode().abspath

make_cmd = 'make'
if GetOption('kernel-dir'):
    make_cmd += ' KERNELDIR=' + GetOption('kernel-dir')
    make_cmd += ' SANDESH_HEADER_PATH=' + Dir(env['TOP'] + '/vrouter/').abspath
    make_cmd += ' SANDESH_SRC_ROOT=' + '../build/kbuild/'
    make_cmd += ' SANDESH_EXTRA_HEADER_PATH=' + Dir('#tools/').abspath

kern = env.Command('vr_linux_test.ko', makefile, make_cmd, chdir=dp_dir)
#vrouter_suite.append(kern)

# CFLAGS
env.Append(CCFLAGS = '-g')

env.Replace(LIBPATH = env['TOP_LIB'])
env.Append(LIBPATH = ['../host', '../sandesh', '../dp-core'])
env.Replace(LIBS = ['dp_core', 'vrouter', 'dp_sandesh_c', 'vrouter', 'dp_core', 'dp_sandesh_c', 'dp_core', 'sandesh-c', 'cmocka'])

test_dep_srcs = ['common_test.c']

dp_core_test = VRouterEnv.MakeTestCmd(env, 'dp_core_test', vrouter_suite, test_dep_srcs)

test = env.TestSuite('vrouter-test', vrouter_suite)
env.Alias('vrouter:test', test)
Return('vrouter_suite')
